LIT-Protocol/docs

docs/SDK/installation.md

@glitch003 fixed polyfills issue by removing @cosmjs/amino package so react instruction no longer needed

Fix: @chris fixed polyfills issue so no longer need react instruction

---

docs/Support/faq.md
docs/intro/rollup.mdx

- adds an explicit note to Chronicle info page for requiring test token to mint PKPs.

add lit test token note for pkp minting

---

docs/resources/supportedChains.md
docusaurus.config.js

Previously links for `Edit this page` were redirecting to broken links on the docs GitHub repo. This PR fixes the broken links and now correctly links to the right pages.
Hopefully in the future, this makes it easier for folks to contribute to the docs!

Fix broken linking

---

docs/network/feature-matrix.md
versioned_docs/version-2.0/resources/networkMatrix.md
versioned_sidebars/version-2.0-sidebars.json

Added back in the Lit Network matrix to V2 docs (will import from V3)
- [-] Bug fix (non-breaking change which fixes an issue)
Link to the relevant updated sections in the Netlify preview: https://deploy-preview-130--lit-dev-docs.netlify.app/v2/resources/networkMatrix

Lit network page to v2

---

docs/migration/overview.md

Closes LIT-1553.
This PR:
- Updates the migration overview page with more elaborate details and instructions on migrating between old and new encryption schemes.
General

Add instructions for migrating between encryption schemes

---

docs/sdk/authentication/session-sigs/auth-methods/email-sms.md
versioned_docs/version-2.0/sdk/explanation/authentication/sessionSigs/authMethods/email-sms.md

- Removes stale documentation for `OTP` authentication on sdk v2 where repatcha implementations are outlined which where not merged into the sdk. if we wish to add it back at another point in time we can add the documentation back to this page
- Adds more context to session signature signing examples for `OTP` auth method

remove recaptcha, add more session signature info

---

docs/sdk/installation.md

Fixed a Bug in the Installation guide, that references the wrong LitClient class for the server-side implementation.
The code example showed `LitNodeClient`, but the actual name is `LitNodeClientNodeJs`.
Reference: https://github.com/LIT-Protocol/js-sdk/blob/master/packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts#L97
General

Fix LitNodeClient reference in installation docs for NodeJs

---

docs/sdk/wallets/claimable-keys/usage.md

Types were too hard to find without wading through code, so I added the import statement and also believe I have fixed the types using types that exist (unless there's a ContractClaimProcessor I am unaware of?)
Fix to documentation

Update Creating and Claiming

---

.husky/pre-commit
docs/resources/supported-chains.md
package.json
updateChains.js
yarn.lock

In the v3 docs we pull the latest chains from v2 SDK hence the chains aren't updated.
Use `@lit-protocol/constants@cayenne` instead of `@lit-protocol/constants` which downloads the latest v3 SDK's constant.
Reorganized the v3 docs "Supported Blockchains" to match the updated corresponding v2 docs.
General

fix: Use Cayenne constants for v3 chains

---

netlify.toml

* Updated `netlify.toml` to point to V3
- Re-directs the homepage to v3 instead of v2
General

Updated re-directs to V3

---

docs/sdk/authentication/session-sigs/get-session-sigs.md

`LitAbility.AccessControlDescription` is corrected as `LitAbility.AccessControlConditionDecryption` in https://developer.litprotocol.com/v3/sdk/authentication/session-sigs/get-session-sigs/

Fixed typo in session signature docs

---

docs/sdk/authentication/auth-sig.md
docs/sdk/authentication/session-sigs/get-session-sigs.md
docs/sdk/authentication/session-sigs/intro.md

Update examples to use the latest blockhash while crafting the authSig/sessionSig as its nonce.
General

feat: Use latest blockhash for nonce while crafting authSig/sessionSigs

---

docs/sdk/authentication/auth-sig.md
docs/sdk/serverless-signing/quick-start.md
package.json
yarn.lock

Update `checkAndSignAuthMessage` & `signAndSaveAuthMessage` to use the blockhash from the client as its nonce.
General

feat: Update authSig generation to use blockhash as its nonce

---

docs/sdk/wallets/minting.md

- Adds more examples for `eth wallet provider` for creating new pkp's with type `EthWallet`
provides examples for 
- In memory wallet
- Using `web3` provider for extension requests.
General

add more to examples of eth wallet provider

---

docs/sdk/authentication/session-sigs/auth-methods/social-login.md

This PR adds an example for users that want to change the google oauth context they are use instead of relying on our hosted login server
General

add example for users that want to change the google oauth flow

---

docs/sdk/serverless-signing/quick-start.md
docs/sdk/wallets/minting.md

To be published together with https://github.com/LIT-Protocol/js-sdk/pull/334
General

Rename auth method scope naming from OnlySignMessages to PersonalSign

---

docs/sdk/authentication/auth-sig.md

This is for Hot Wallet Signing, creating AuthSig in the backend
The nodes will throw the error: `Session key expiration time is not set`
```js
// expirtaion time in ISO 8601 format
const expirationTime = new Date(
Date.now() + 1000 * 60 * 60 * 24 * 7 * 10000
).toISOString();
const siweMessage = new siwe.SiweMessage({
domain,
address: wallet.address,
statement,
uri: origin,
version: '1',
chainId: '1',
expirationTime,
});
```
General

Added expiration time to SIWE message

---

docs/migration/overview.md

PKP Ethers requires the some polyfills which is missing from the CRA section: https://developer.litprotocol.com/v3/migration/overview/#using-create-react-app-cra
Create a new sub-section below it to state the required polyfills and how to do so. Install & add the following to config-overrides.js just as mentioned here: https://developer.litprotocol.com/v3/migration/overview/#using-create-react-app-cra
```js
'http': require.resolve('stream-http'), // Add this line
'https': require.resolve('https-browserify'), // Add this line
'url': require.resolve('url/'), // Add this line
'zlib': require.resolve('browserify-zlib'), // Add this line
'assert': require.resolve('assert/'), // Add this line
```
Link to the relevant updated sections in the Netlify …

Update Polyfill with CRA for PKP Ethers

---

docs/sdk/wallets/auth-methods.md

Missing how to add Lit Action as an AuthMethod from the docs.
Have to use `utils.getBytesFromMultihash` to convert ipfsCid from base58 encoding to byte-like. Add it to the docs on this page as a note: https://developer.litprotocol.com/v3/sdk/wallets/auth-methods
General

Added how to add Lit Action as an Auth Method

---

docs/sdk/capacity-credits.md

- quick fixes to default network capacity, and the `network` flag in `LitNodeClient` usage

fix network flag to main net testnet

---

docs/sdk/authentication/session-sigs/auth-methods/add-remove-auth-methods.md
package.json
yarn.lock

Add a note to estimate gasLimit for adding and removing auth methods.
They can either estimate it at their end using -  https://developer.litprotocol.com/v3/sdk/authentication/session-sigs/auth-methods/add-remove-auth-methods/#estimating-gas OR can play around and set a sufficiently high gas fees.
General

Added note for estimating gasLimit for tx

---

docs/sdk/capacity-credits.md
package.json
yarn.lock

Capacity credits are much simpler to be minted from the Lit PKP Explorer but haven't mentioned this in the docs
Here - https://developer.litprotocol.com/v3/sdk/capacity-credits/
Reference - https://www.notion.so/litprotocol/Simplify-Mainnet-Migration-abb502a527144ec5b2aecc63d247215f#8b51454a526d48459b6927987467d813
General

Added capacity credit NFTs can be minted from the Lit Explorer

---

docs/network/migration-guide.md
package.json
yarn.lock

We now use ID encryption which is different from Jalapeno & Serrano
Devs find it difficult to understand how to do this migration
Create an example for doing so explaining each step & differences between the two encryption schemes
General

Example to decrypt from old and encrypt in new network

---

docs/migration/overview.md

`Error: Cannot find module 'jszip/dist/jszip.js'` in SDK v3.2.3
General
Was this error restricted to CRA or it was also in an NodeJS app? @Aaryan-R-S 

fix: Add jszip polyfill

---

docs/resources/supported-chains.md
docs/sdk/serverless-signing/key-claiming.md
package.json
yarn.lock

Add a section on calculating your key id to this page: https://developer.litprotocol.com/v3/sdk/serverless-signing/key-claiming in a section called "calculating your key id".
General

fix(keyClaim): add calculating key id section

---

docs/sdk/wallets/minting-methods/mint-via-multiple-auth-methods.md
docs/sdk/wallets/minting.md
sidebars.js

Create example to mint PKP with multiple authMethods
Add it to the docs
It can be achieved by both LitAuthClient & the ContractsSDK
Here's an example of doing it with the former: https://github.com/LIT-Protocol/js-sdk/blob/master/e2e-nodejs/group-pkp-auth-method/test-pkp-auth-method-multiple-auth-method-mint.mjs#L28
Other examples exists for doing it with the later in the SDK repo: https://github.com/LIT-Protocol/js-sdk/blob/251482b90761e9e0e734cb08c0c4a93b563b6869/e2e-nodejs/group-contracts/test-contracts-write-mint-a-pkp-and-set-scope-1-advanced.mjs#L40
General

Add minting with multiple Auth Methods via LitAuthClient and ContractsSDK

---

docs/sdk/serverless-signing/key-claiming.md

It's not clear from the docs where we're getting 'foo' from:
```js
const res = await client.executeJs({
authSig,
code: (async () => {
Lit.Actions.claimKey({keyId});
})();,
authMethods: [],
jsParams: {
keyId
},
});
let client = new LitContracts(signer: "<your pkp wallet or other signer>");
let tx = await contractClient.pkpNftContract.write.claimAndMint(2, res.claims['foo'].derivedKeyId, res.claims['foo'].signatures);
```
at https://developer.litprotocol.com/v3/sdk/serverless-signing/key-claiming
General

fix(keyClaim): fix parameters to executeJs in example

---

docs/sdk/wallets/auth-methods/lit-auth-methods/social-login.md
package.json
yarn.lock

Add import statement for `isSignInRedirect` in docs example
At - https://developer.litprotocol.com/v3/sdk/wallets/auth-methods/lit-auth-methods/social-login#handling-the-redirect
Fixes - [LIT-2823](https://linear.app/litprotocol/issue/LIT-2823/add-import-statement-for-issigninredirect-in-docs-example)
General

Add import statement for `isSignInRedirect` in docs example

---

docs/sdk/serverless-signing/conditional-signing.md
docs/sdk/serverless-signing/fetch.md
docs/sdk/serverless-signing/key-claiming.md
docs/sdk/serverless-signing/overview.md

This PR corrects the typo "severless" to the correct form of "serverless."

fix: typo severless -> serverless

---

docs/sdk/access-control/quick-start.md

The `Mint Capacity Credits and Delegate Usage` section includes the first time the contracts SDK is mentioned, I think it would make sense to include an installation step as all previous sections only require the main SDK to be installed

Add installation step for contracts SDK in decryption guide

---

docs/sdk/access-control/quick-start.md

This PR is merging into `main`, not sure if we prefer merging into a different branch
Missing a space in the [import code example](https://developer.litprotocol.com/v3/sdk/access-control/quick-start#install-and-import-the-lit-sdk):

Missing space in package import code example

---

docs/sdk/installation.md

Corrects \`litNodeClient\`\` to \`litNodeClient\`

Fix typo in `installation.md`

---

docs/sdk/serverless-signing/quick-start.md
docs/sdk/wallets/minting-methods/mint-via-contracts.md
docs/sdk/wallets/quick-start.md

In : 
- https://developer.litprotocol.com/v3/sdk/wallets/quick-start
- https://developer.litprotocol.com/v3/sdk/serverless-signing/quick-start
The `accessToken` in the `authMethod` is defined as : "...". 
This code generates an error.
I assume the correct version is : `accessToken: JSON.stringify(authSig),`
General

Update documentation : replace '...' accessToken by 'JSON.stringify(authSig)'

---

docs/sdk/migrations/6.0.0.md

Adds a note in the `Clarifications` section (at the bottom of the doc page) to tell users:
> On the Lit network, `cayenne`, payment for network usage is **not** required. However, when migrating to `v6`, if you use Capacity Credits or are delegating them, your code should still be functional as long as the Capacity Credits you're using were minted on the `cayenne` network. Capacity Credits minted on `manzano` or `habanero` or **not** valid on the `cayenne` network.

Add capacity credits note

---

docs/network/migration-guide.md
docs/sdk/access-control/quick-start.md
docs/sdk/installation.md
docs/sdk/serverless-signing/quick-start.md
docs/sdk/wallets/quick-start.md
versioned_docs/version-2.0/sdk/explanation/installation.md
versioned_docs/version-2.0/sdk/explanation/migration.md

Updates our `NodeJS` version requirements to `19` from `16` for `crypto` native support if running in NodeJS

ref: node version update

---

docs/api-reference/latest.md

Changes docs section title from v4 to latest, updates title within the doc page to reference latest sdk doc link.

Update and rename v4-sdk.md to latest.md

---

docs/sdk/serverless-signing/combining-signatures.md

Fixes issue with `signAndCombineEcdsa` example where an `ethers` util method is not correctly called using the injected `ethers` library.

ref: fix sign and combine example

---

docs/sdk/serverless-signing/combining-signatures.md

- Fixes `signAndCombineEcdsa` basic example with 32 byte hashing before signing.

fix: add 32 byte hashing to signAndCombineEcdsa example

---

docs/sdk/paying-for-lit/payment-delegation-db.md
sidebars.js

The corresponding developer guide code is [here](https://github.com/LIT-Protocol/developer-guides-code/pull/18)
This PR inits the Payment Delegation DB docs that covers how to use the `register-payer` and `add-users` endpoints for the Relayer API
CC @alexvotofuture

Init Payment Delegation DB doc

---

docs/sdk/wrapped-keys/custom-wrapped-keys.md
docs/sdk/wrapped-keys/exporting-wrapped-key.md
docs/sdk/wrapped-keys/generating-wrapped-key.md
docs/sdk/wrapped-keys/getting-wrapped-key-metadata.md
docs/sdk/wrapped-keys/importing-key.md
docs/sdk/wrapped-keys/overview.md
docs/sdk/wrapped-keys/sign-message.md
docs/sdk/wrapped-keys/sign-transaction.md
docs/sdk/wrapped-keys/storing-wrapped-key-metadata.md

In the wrapped keys section:
Replaced every URL that included a specific hash to instead include the master branch.
Deleted some duplicate text.

Fixed hash URLs/Removed duplicate text

---

docs/sdk/wrapped-keys/generating-wrapped-key.md

Add warning for not using Wrapped Keys for Production (Habanero).
General

feat: Add warning for Habanero Wrapped Keys

---

docs/sdk/serverless-signing/combining-decryption-shares.md

Changed the `Using IPFS ID as an Access Control Parameter` example to be accurate.

Changed the IPFS ID Access Control Parameter Example

---

docs/user-wallets/pkps/quick-start.md

The code snippet of user-wallets/programmable-key-pairs/quickstart/delegate-usage-to-your-pkp metions `signer` as a param. Corrected it to use `dAppOwnerWallet`
General

docs(user-wallets): updated quickstart:delegate_usage_to_your_pkp

---

docs/tools/event-listener.md
docs/tools/getlit-cli.md

I added callouts to the tools pages (getLit CLI and event listener) to let devs know that they are currently incompatible with the latest SDK

updates to tools page

---

docs/sdk/authentication/session-sigs/get-lit-action-session-sigs.md
docs/sdk/authentication/session-sigs/get-pkp-session-sigs.md
docs/sdk/authentication/session-sigs/get-session-sigs.md
docs/sdk/authentication/session-sigs/intro.md
docs/sdk/authentication/session-sigs/siws-pkp-session-sigs.md

Added the below warning to the Session Signatures intro and generation pages:

SessionSigs No Cache Warning

---

docs/learn/overview/how-it-works/lit-networks/mainnets.md
docs/learn/overview/how-it-works/lit-networks/testnets.md

Slightly refactors the Lit network pages:
- [Mainnets](https://developer.litprotocol.com/connecting-to-a-lit-network/mainnets)
- [Testnets](https://developer.litprotocol.com/connecting-to-a-lit-network/testnets)

Init Mainnets and Testnets pages

---

docs/sdk/serverless-signing/web-assembly.md
sidebars.js

Just adds a wasm page with info on how to use it on datil-dev, since we just deployed support for it to that network.

Add docs on wasm

---

docs/sdk/access-control/quick-start.md
docs/sdk/serverless-signing/processing-validation.md
docs/user-wallets/wrapped-keys/sign-transaction.md

Changed example to code to showcase the LitNodeClient to use the litNetwork: datil-dev rather than serrano.
Fixes # DREL - 396
- [ x] Bug fix (non-breaking change which fixes an issue)
General
- [ x] I have performed a self-review of my code
- [x ] I have fixed all grammar issues (can use an AI tool to check), and explanations are in active voice
- [ x] I have checked the additions are concise
- [x ] Language is consistent with existing documentation
- [x ] My changes generate no new warnings
- [ x] Any dependent changes have been merged and published (ie. SDK changes, node dependencies)
- [n/a ] included a beginner friendly explanation
- [n/a ] included a basic technical introduction and code sample
- [n/a …

Update serrano to datil-dev

---

docs/user-wallets/wrapped-keys/sign-transaction.md

Made changes to signTransactionWithEthereumEncryptedKey and signTransactionWithSolanaEncryptedKey links, should be working now.
Fixes DREL - 388
- [ x] Bug fix (non-breaking change which fixes an issue)
General
- [ x] I have performed a self-review of my code
- [ x] I have fixed all grammar issues (can use an AI tool to check), and explanations are in active voice
- [ x] I have checked the additions are concise
- [ x] Language is consistent with existing documentation
- [ x] My changes generate no new warnings
- [ x] Any dependent changes have been merged and published (ie. …

Doc links not working for signTransactionWithEthereumEncryptedKey and signTransactionWithSolanaEncryptedKey

---

docs/sdk/access-control/quick-start.md
docs/user-wallets/wrapped-keys/sign-transaction.md

Included import statement that allows for encryption to happen and not run into TypeError: LitJsSdk.encryptString is not a function.
Fixes DREL - 402
- [ x] Bug fix (non-breaking change which fixes an issue)
General
- [ x] I have performed a self-review of my code
- [x ] I have fixed all grammar issues (can use an AI tool to check), and explanations are in active voice
- [x ] I have checked the additions are concise
- [x ] Language is consistent with existing documentation
- [x ] My changes generate no new warnings
- [ x] Any dependent changes have been merged and published (ie. SDK changes, node dependencies)
- [ n/a] included a beginner friendly explanation
- [ n/a] included a basic technical introduction …

Update quick start encryption

---

docs/intro/first-request/making-first-signing.md

Update "Signing Data" with PKP docs.`ethers.utils.recoverAddress` returns 0x${publicKey} (lit doesn't prefix with 0x in responses to mint/sign) so the assertion from docs (`recoveredPubkey === pkpInfo.publicKey`) fails.
Demo: https://stackblitz.com/edit/lit-pkp-signed-pubkey-mismatch-demo?file=src%2Fmain.ts
Documentation update
General

Adjust docs for ethers recoverPublicKey prefixing the public key with 0x

---

docs/integrations/storage/irys.md
docs/sdk/access-control/encryption.md
docs/sdk/access-control/quick-start.md

This PR is a demo on how SDK consumers can [de]compress the data they encrypted with Lit
Compression using JsZip was removed from the SDK on v7 [PR#621](https://github.com/LIT-Protocol/js-sdk/pull/621) so it now requires this extra code outside the SDK, but also allows customer to use their custom compression strategy
```
"scripts": {
"run:zipAndEncryptString": "tsx ./src/zipAndEncryptString.ts",
"run:zipAndEncryptMultipleFiles": "tsx ./src/zipAndEncryptMultipleFiles.ts",
"run:zipFileAndBundleWithMetadata": "tsx ./src/zipFileAndBundleWithMetadata.ts"
},
```

compressing removed from sdk on v7, replaced with uint8array method
