docs/ExamplesAndGuides/EncryptAndDecrypt/_category_.json
docs/ExamplesAndGuides/EncryptAndDecrypt/decryption.md
docs/ExamplesAndGuides/EncryptAndDecrypt/encryption.md
docs/ExamplesAndGuides/EncryptAndDecrypt/installation.md
docs/ExamplesAndGuides/EncryptAndDecrypt/learn_more.md

Client side basic to using the Lit encryption and decryption functions
.

Encrypting and Decrypting

---

docs/supportedChains.md
src/css/custom.css

Update custom css for h2 and h3 tag

---

docs/AccessControlConditions/EVM/_category_.json
docs/AccessControlConditions/EVM/basicExamples.md
docs/AccessControlConditions/EVM/customContractCalls.md
docs/AccessControlConditions/EVM/poap.md
docs/AccessControlConditions/EVM/timelock.md
docs/AccessControlConditions/intro.md
docs/LitTools/shareModal.md
netlify.toml

Moved documentation around to create easier experience of finding access control conditions. Also wrote in some more description on where to go / how to use the share modal.

Update access control docs

---

docs/SDK/installation.md
docs/SDK/intro.md

Since Lit SDK is the title, having JS SDK will sound confusing

Change JS SDK to Lit SDK 

---

docs/ToolsAndExamples/SDKExamples/dynamicContent.md

Update dynamic content page

---

src/components/CardSections/QuickStart.jsx

Update quickstart with on-chain metada link

---

docs/coreConcepts/Wallets/examples.md
docs/coreConcepts/Wallets/intro.md
src/components/CardSections/CoreConcepts.jsx

Update wallet section

---

docs/LitActions/helloWorld.md

Remove bash and format bash installation snippet

Update LitAction helloWorld.md - Install the SDK and get a PKP

---

docs/pkp/minting.md

- Fixes dead links in the `Minting a PKP` page which link to internal docs

fix stale links

---

docs/pkp/authHelpers.md

- Adds email/sms to auth helpers page

add email sms to auth helpers

---

docs/SDK/Explanation/authentication/authSig.md

**Summary**
Generating auth sigs on the server-side is hidden away in an example, so added the example to the auth sig page.

feat: surface node authsig example

---

docs/SDK/examples.md
docs/resources/supportedChains.md

Put the OAuth demo repo in the examples section.

Put OAuth PKP repo in examples section

---

.github/pull_request_template.md
docs/resources/supportedChains.md

Including a template for PR updates to the docs - making sure the language is consistent across the docs.
Introducing new feature (non-breaking change which adds functionality)
General

add in template for each pull req

---

Ecosystem/projects.md
docs/resources/glossary.md
docs/sdk/access-control/jwt-auth.md
docs/sdk/authentication/overview.md
docusaurus.config.js
src/components/CardSectionsV2/CoreConcepts.jsx
src/components/SDKCardSectionsV2/Actions.jsx
versioned_docs/version-2.0/LitActions/intro.md
versioned_docs/version-2.0/ToolsAndExamples/Integrations/bundlrxarweave.md
versioned_docs/version-2.0/ToolsAndExamples/SDKExamples/OnchainMetadata/introduction.md
versioned_docs/version-2.0/intro/usecases.md
versioned_docs/version-2.0/intro/whatIsLitProtocol.md
versioned_docs/version-2.0/pkp/authHelpers/overview.md
versioned_docs/version-2.0/pkp/intro.md
versioned_docs/version-2.0/pkp/walletconnect.md
versioned_docs/version-2.0/resources/glossary.md
versioned_docs/version-2.0/sdk/explanation/authentication/overview.md
versioned_docs/version-2.0/sdk/explanation/authentication/sessionSigs/getSessionSigs.md
versioned_docs/version-2.0/startHere/usecases.md
versioned_docs/version-2.0/support/faq.md

Bug fixes in V2 and some in V3 docs. First pass of broken links since these PR's can get pretty big. 
General

pass #1 of bug fixes

---

docusaurus.config.js

Remove unreleased note for SDK V3
General
- [s] I have performed a self-review of my code
- [s] I have fixed all grammar issues (can use an AI tool to check), and explanations are in active voice
- [s] I have checked the additions are concise
- [s] Language is consistent with existing documentation
- [s] My changes generate no new warnings
- [s] Any dependent changes have been merged and published (ie. SDK changes, node dependencies)

New top banner for SDK V3 callout

---

docs/resources/contracts.md
versioned_docs/version-2.0/resources/contracts.md

Update the contracts page to point to network repo
Fix issue brought up by partners
General
[Lit Contracts SDK](https://github.com/LIT-Protocol/js-sdk/tree/master/packages/contracts-sdk) for SDK V3 on backlog to update the example

Update contracts pages

---

docs/sdk/claimable-keys/usage.md

fix api key param

---

docs/intro/overview.mdx
docs/intro/what-is-lit-protocol.md

Update to what is lit and overview

---

.github/workflows/reindex-crawler.yml

trying to fix github reindex workflow

try to fix reindex github workflow

---

docs/sdk/authentication/session-sigs/auth-methods/email-sms.md

Replaces the `Email /SMS` auth with Stytch examples and explanation as v3 was using outdated information from the V2 system. 
These updates include new `Auth Factor` support to harden the security model. 
General

update email / sms docs for stytch

---

versioned_docs/version-2.0/sdk/explanation/contracts.md

Adds information on using the `contract-sdk` for on chain operations.
General

add contract docs

---

docs/sdk/wallets/auth-methods.md

Basic docs on auth method scopes

added some info on auth method scopes

---

docs/sdk/authentication/session-sigs/auth-methods/add-remove-auth-methods.md
docs/sdk/authentication/session-sigs/get-session-sigs.md
docs/sdk/authentication/session-sigs/intro.md
versioned_docs/version-2.0/resources/glossary.md
versioned_docs/version-2.0/resources/supportedChains.md
versioned_docs/version-2.0/sdk/explanation/authentication/sessionSigs/getSessionSigs.md
versioned_docs/version-2.0/support/stateOfNetwork.md

1. Update the "Supported Blockchains" section to display chains based on Lit Networks: Jalapeno & Serrano on v2 docs & Cayenne on v3 docs
2. Fix broken links
General
If I have added a new concept, I have (N/A)

feat: Update supported chains based on Lit Network v2 Docs

---

docs/resources/glossary.md
docs/sdk/wallets/auth-methods.md
docs/sdk/wallets/minting.md

added examples of setting scopes to docs
added description of scopes to the 'auth methods' and 'minting a pkp' section of the dev docs. 
- [ x] Introducing new feature (non-breaking change which adds functionality)
General
- [ x] I have performed a self-review of my code
- [ x] I have fixed all grammar issues (can use an AI tool to check), and explanations are in active voice
- [x ] I have checked the additions are concise
- [x ] Language is consistent with existing documentation
- [x ] My changes …

scope additions

---

docs/sdk/installation.md

A small typo is fixed in the installation docs

---

security.txt

See: https://linear.app/litprotocol/issue/LIT-2003/create-securitytxt-file-in-our-repos-so-people-can-know-where-to

Added security.txt

---

docs/migration/overview.md

Adds documentation for addressing bundling issues with CRA
General

add cra docs

---

docs/integrations/aa/alchemy-account-kit.md

- Adds doc link for Alchemy AA signer docs.
General

add doc link to aa signer docs

---

docs/resources/supported-chains.md
updateChains.js
yarn.lock

feat: Sort chains by name

---

docs/network/migration-guide.md
sidebars.js

Added v0 migration guide to the docs
General

migration instructions

---

docs/concepts/capacity-credits-concept.md
docs/integrations/aa/alchemy-account-kit.md
docs/network/networks/mainnet.md
docs/network/networks/testnet.md
docs/network/rollup.mdx
docs/sdk/capacity-credits.md
docs/sdk/serverless-signing/quick-start.md
docs/sdk/wallets/intro.md
sidebars.js
yarn.lock

Update token name

---

docs/concepts/capacity-credits-concept.md
docs/concepts/pkps-as-wallet.md
docs/intro/overview.mdx
docs/resources/how-it-works.md
docs/sdk/access-control/encryption.md
docs/sdk/capacity-credits.md
docs/sdk/serverless-signing/overview.md
docs/sdk/serverless-signing/quick-start.md
docs/sdk/wallets/intro.md

Updating banners with v0 announcement.
LINKS WILL NEED TO BE UPDATED ONCE V0 IS LIVE
General

updating banners

---

docs/sdk/wallets/auth-methods.md

fix: scope enum

---

docs/network/migration-guide.md
docs/sdk/installation.md

fixes an issue where we where using the wrong syntax for sdk `install` and `import` statements.

fix tag usage

---

learningLab/intro-to-lit/network.md

Corrected a small typo at https://developer.litprotocol.com/learninglab/intro-to-lit/network/#objectives
General

Fixed small typo in networks page

---

Ecosystem/community.md

Make Community Resources section more user friendly
Make this page https://developer.litprotocol.com/ecosystem/community/ more interactive as many users visit this page to communicate with us!
General

Improved formatting and UI of community page

---

docs/sdk/capacity-credits.md

the function `mintCapacityCreditsNFT` now support different periods based on user context, they can now pass in either `requestsPerDay`, `requestsPerSecond` or `requestsPerKilosecond` to the function
General

update cc usage

---

docs/integrations/storage/ceramic-example.md

Updating links in Ceramic guide
Simple link updates to docs

Updating links in Ceramic guide

---

docs/concepts/capacity-credits-concept.md
package.json
yarn.lock

Processing Requests & Capacity Credits have the same content
Remove the former form this page: https://developer.litprotocol.com/v3/concepts/capacity-credits-concept/
General

Removed duplicate content from Paying For Usage section

---

docs/sdk/access-control/encryption.md
package.json
yarn.lock

At https://developer.litprotocol.com/v3/sdk/access-control/encryption#encrypting
Step 3 of 'steps to encrypt' ends with "You'll need to pass in these" and nothing else. 
General

Fixed Encryption Page

---

docs/network/migration-guide.md
package.json
yarn.lock

Explicitly mention that the PKP have to be migrated by them. As mentioned in this Notion page section: https://www.notion.so/litprotocol/Simplify-Mainnet-Migration-abb502a527144ec5b2aecc63d247215f?pvs=4#6a3f286082dc41a8b1bac191f2ebe232
Here - [https://developer.litprotocol.com/v3/network/migration-guide/#:~:text=We have an example script here that will perform the re-minting for you%3A](https://developer.litprotocol.com/v3/network/migration-guide/#:~:text=We%20have%20an%20example%20script%20here%20that%20will%20perform%20the%20re%2Dminting%20for%20you%3A)
General

Mentioned that PKP have to be migrated

---

docs/sdk/capacity-credits.md

We should specifically state that the siwe message that's being signed in the callback has to be a delegatee wallet
General

fix: cc example

---

docusaurus.config.js
package.json
yarn.lock

Fixes #243 
In https://developer.litprotocol.com/v3/sdk/access-control/condition-types/unified-access-control-conditions/
For [EVM Basic Conditions](https://developer.litprotocol.com/v3/sdk/access-control/access-control/evm/basic-examples), also known as classic "Access Control Conditions", use the string evmBasic
For [EVM Custom Contract Conditions](https://developer.litprotocol.com/v3/sdk/access-control/access-control/evm/custom-contract-calls), use the string evmContract
For [Solana RPC Conditions](https://developer.litprotocol.com/v3/sdk/access-control/access-control/other-chains/sol-rpc-conditions), use the string solRpc
For [Cosmos or Kyve Conditions](https://developer.litprotocol.com/v3/sdk/access-control/access-control/other-chains/cosmos-conditions), use the string cosmos
Every …

Fixed docusaurus config file

---

docs/resources/supported-chains.md
updateChains.js

At https://developer.litprotocol.com/v3/resources/supported-chains remove specific network name - `Cayenne`.
Trying to update docs for it!
General

Remove Cayenne from the title in Supported Blockchains section

---

docs/network/migration-guide.md
docs/sdk/installation.md

Added documentation for new `disconnect()` method on LitNodeClient.
This is a new feature that will be added in 4.x - Do we have a process/policy for how to describe these types of additions?
General
SDK changes that add this functionality are in this PR: https://github.com/LIT-Protocol/js-sdk/pull/398

docs: LIT-2560 - Add documentation for litNodeClient.disconnect()

---

docs/resources/supported-chains.md
docs/support/faq.md
package.json
sidebars.js
yarn.lock

Fixing broken link on FAQ page. Adjusting title Serverless Signing to -> Serverless Signing (Lit Actions)
General

fix(faq): fix broken link and modify title

---

docs/network/networks/mainnet.md
docs/network/networks/testnet.md
src/css/custom.css

added coloring to the tables to make it immediately obvious which networks to use

better descriptions of the networks in the tables.  

---

docs/sdk/access-control/intro.md
docs/sdk/access-control/quick-start.md
docs/sdk/authentication/auth-sig.md
docs/sdk/authentication/session-sigs/get-session-sigs.md
docs/sdk/capacity-credits.md
docs/sdk/serverless-signing/quick-start.md
docs/sdk/wallets/quick-start.md
versioned_docs/version-2.0/accessControl/intro.md
versioned_docs/version-2.0/resources/howItWorks.md
versioned_docs/version-2.0/sdk/explanation/encryption.md

- updates latest documentation to use the `5.0.0` release context
https://github.com/LIT-Protocol/js-sdk/releases/tag/v5.0.0

ref: Update docs for 5.0.0 sdk release

---

docs/additional-examples.md
docs/additional-examples/intro.md
docs/network/migration-guide.md
docs/resources/how-it-works.md
docs/sdk/access-control/intro.md
docs/sdk/serverless-signing/overview.md
docs/sdk/wallets/intro.md
package.json
sidebars.js
versioned_sidebars/version-2.0-sidebars.json
yarn.lock

Docs updates

---

docs/sdk/migrations/6.0.0.md
sidebars.js

v6 migration guide

---

docs/sdk/serverless-signing/broadcast-and-collect.md
docs/sdk/serverless-signing/combining-decryption-shares.md
docs/sdk/serverless-signing/combining-signatures.md
docs/sdk/serverless-signing/encryption.md
docs/sdk/serverless-signing/get-rpc-url.md
docs/sdk/serverless-signing/run-once.md
sidebars.js

Adds documentation for the new Lit Action plus features under `Decentralized Compute (Lit Actions)`
completes the new feature additions to `Lit.Actions` api with the following new methods documented
- decryptAndCombine()
- Runs decryption across the nodes, and combines the shares, and returns the decrypted thing
- signAndCombineEcdsa()
- Runs signing across the nodes, and combines the shares, and returns the signature
- runOnce()
- Runs something on only one node.  Can return a value by broadcasting it to all nodes.
- *getRpcUrl()*
- *gets a local nodes RPC url.*
- broadcastAndCollect()
- Sends a value to all the nodes, and collects values from all the nodes.  The result is an array of the values from all the other nodes.
Link …

Feature/lit 2726 Lit Action Plus Documentation

---

docs/sdk/serverless-signing/combining-decryption-shares.md

Adds link to api key guide fir lit action decryption

feat: add decrypt api key

---

docs/api-reference/latest.md
docs/api-reference/v1-sdk.md
docs/api-reference/v2-sdk.md
docs/api-reference/v3-sdk.md
docs/sdk/access-control/encryption.md
docs/sdk/access-control/jwt-auth.md
docs/sdk/access-control/quick-start.md
docs/sdk/authentication/auth-sig.md
docs/sdk/serverless-signing/combining-signatures.md
docs/sdk/serverless-signing/dependencies.md
docs/sdk/serverless-signing/eip191.md
docs/sdk/serverless-signing/quick-start.md
docs/sdk/wallets/quick-start.md
docusaurus.config.js
sidebars.js

Some doc fixes that were requested by our customers.
- Remove navbar dropdown fov v2/v3 docs version
- Distinguish SDK versions in our docs from "v6/v5/v4/v3/v2" to latest vs legacy SDK versions like in API reference section
- Link APIs in API Reference section
- Use "SDK v4 and above" here - https://developer.litprotocol.com/v3/sdk/serverless-signing/quick-start#install-and-import-the-lit-sdk and in other quick start too
- Minor correction on EIP191 Lit Action page
- Nitpicks on lit action docs pages
- Reference sessionSigs instead of authSigs in docs
- Update this [Wallet Signatures/AuthSigs doc page](https://developer.litprotocol.com/v3/sdk/authentication/auth-sig) with a warning about v6 dropping support for it, except for decryption.
Link …

Some doc fixes

---

docs/sdk/serverless-signing/combining-decryption-shares.md
docs/sdk/serverless-signing/encryption.md
sidebars.js

- Updates `Encryption` features within Lit Actions to the new api
- Adds explainer for `:currentActionIpfsId`
- https://github.com/LIT-Protocol/lit-assets/pull/1155

feat: add api updates to lit action encryption/decryption features

---

docs/network/rollup.mdx
sidebars.js
src/components/AddRollupButton.jsx

change chronicle url in the docs

---

docs/support/faq.md

@joshLong145 mentioned that WASM is no longer supported

Update faq.md to say WASM is not supported

---

docs/sdk/authentication/session-sigs/get-session-sigs.md

Changed this: https://developer.litprotocol.com/sdk/authentication/session-sigs/get-session-sigs page to a working example of getting session sigs. Added a couple comments. Encapsulated the code within a function.

Updated the Generating Session Sigs page

---

docs/sdk/paying-for-lit/payment-delegation-db.md
docs/sdk/wrapped-keys/custom-wrapped-keys.md
docs/sdk/wrapped-keys/exporting-wrapped-key.md
docs/sdk/wrapped-keys/generating-wrapped-key.md
docs/sdk/wrapped-keys/getting-wrapped-key-metadata.md
docs/sdk/wrapped-keys/importing-key.md
docs/sdk/wrapped-keys/sign-message.md
docs/sdk/wrapped-keys/sign-transaction.md
docs/sdk/wrapped-keys/storing-wrapped-key-metadata.md

- "datil-dev" -> LitNetwork.DatilDev
- Old RPC URL -> LIT_RPC.CHRONICLE_YELLOWSTONE
- Cayenne -> DatilDev
- manzano -> datil-test
- https://manzano-relayer.getlit.dev/register-payer -> https://datil-test-relayer.getlit.dev/register-payer 
- https://manzano-relayer.getlit.dev/add-users -> https://datil-test-relayer.getlit.dev/add-users

Yellowstone Changes

---

src/pages/state-of-the-network.md

Fixed the notice on the pages. It seems that using the filepath while viewing from different locations does not work. I used the links instead.

Additional Link fixes (minor changes)

---

docs/resources/glossary.md
docs/sdk/authentication/session-sigs/resources-and-abilities.md
docs/sdk/authentication/session-sigs/use-cases.md
versioned_docs/version-2.0/sdk/explanation/authentication/sessionSigs/use-cases.md

RLI to Capacity Credits

---

docs/sdk/authentication/session-sigs/intro.md

Fixed two links in the new sessionsigs docs

Fixed paying for Lit links

---

docs/sdk/access-control/quick-start.md
docs/sdk/authentication/session-sigs/intro.md
docs/sdk/serverless-signing/combining-signatures.md
docs/sdk/serverless-signing/conditional-signing.md
docs/sdk/serverless-signing/quick-start.md
docs/user-wallets/wrapped-keys/sign-transaction.md

Update docs pages for:
sign-and-combine-ecdsa
conditional-signing

Update Lit Actions Advanced Examples

---

src/components/AddRollupButtonYellowstone.jsx

Chronicle Yellowstone Button Fix

---

docs/sdk/serverless-signing/eip191.md

Reworking the docs example to match the updated dev-guides-code example

EIP-191 Rework

---

docs/integrations/aa/candide.md
docs/integrations/aa/overview.md
sidebars.js

Adding the second half of the Candide guide to the Lit docs

Candide Docs

---

docs/integrations/aa/candide.md
sidebars.js

Quickly fixing the sidebars and title for the Candide docs

Changing sidebars

---

docs/sdk/authentication/session-sigs/intro.md

Improve Manually Generating Session Keys section

feat(sessionSigs/accessToken): Manually Generating Session Keys

---

docs/sdk/serverless-signing/overview.md

Adds `Built-in Ethers.js and Lit SDK Support` bullet point

Add bullet point to Lit Action overview

---

docs/user-wallets/pkps/bitcoin/1of1-multi-sig.md
docs/user-wallets/pkps/bitcoin/collaborative.md
docs/user-wallets/pkps/bitcoin/multi-sig.md
docs/user-wallets/pkps/bitcoin/overview.md
docs/user-wallets/pkps/bitcoin/single-sig.md

Some minor touchups I noticed while making the dev guide PR

BTC Guide Fixes

---

.github/workflows/reindex-crawler.yml

Crawler Node Fix

---

package.json
src/theme/SearchBar/index.js
yarn.lock

Preview link: https://lit-docs-cookbook.vercel.app
Cookbook's Ask Cookbook AI assistant and co-pilot is trained on all existing Lit Protocol resources (source code, docs website, etc.) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about using Lit Protocol, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity coding co-pilot.
Ask Cookbook AI can also access context from thousands of data sources indexed by Cookbook.dev in addition to Lit Protocol-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer …

feat: Cookbook Onboard (AI Assistant) integration

---

docs/api-reference/latest.md
docs/api-reference/v6-sdk.md
docs/sdk/migrations/7.0.0.md
sidebars.js
src/components/CardSectionsV3/LearnCode.jsx

quick updates for v7 sdk release. Updated api reference and added migration guide

v7 updates

---

docs/integrations/aa/pimlico.md
docs/user-wallets/pkps/advanced-topics/auth-methods/add-remove-auth-methods.md
docs/user-wallets/pkps/walletconnect.md

[Updates to PKP Wallet Classes](https://linear.app/litprotocol/issue/DREL-337/updates-to-pkp-wallet-classes)

v7 docs: updated pkp wallet classes

---

docs/learn/overview/lit-sdk/overview.md

Inits a new page introducing users to the Lit SDK

Init JS SDK overview page

---

docs/learn/overview/intro.mdx

This page refactors the existing [Overview](https://developer.litprotocol.com/) page

Init Learn intro page

---

docs/learn/overview/how-it-works/overview.md

Refactors the existing [How Does Lit Protocol Work](https://developer.litprotocol.com/resources/how-it-works) page

Init How it Works page

---

docs/learn/overview/how-it-works/lit-networks/migrating-to-datil.md

Slight refactor of the existing [Migrating to Datil](https://developer.litprotocol.com/connecting-to-a-lit-network/migrating-to-datil) page

Init Migrating to Datil page

---

docs/learn/overview/how-it-works/lit-blockchains/chronicle-yellowstone.md
docs/learn/overview/how-it-works/lit-blockchains/chronicle.md
src/components/AddRollupButton.jsx
src/components/AddRollupButtonYellowstone.jsx

Slight refactors the existing pages:
- [Chronicle Yellowstone](https://developer.litprotocol.com/connecting-to-a-lit-network/lit-blockchains/chronicle-yellowstone)
- [Chronicle](https://developer.litprotocol.com/connecting-to-a-lit-network/lit-blockchains/chronicle)

Init Lit Blockchain pages

---

package.json
yarn.lock

Bump Lit constants package version

---

docs/agent-wallet/intro.md

Just a small note describing the root authority of the system

Add LAW Note

---

docs/agent-wallet/intro.md

fix LAW note

---

docs/security/crypto-security.md
src/pages/token-disclaimer.md

added a token disclaimer to the docs

add token disclaimer

---

docs/security/communicating-with-nodes.md
sidebars.js

added a "communicating with the Lit nodes" page to address the question posed by Genius

security update to address Genius query

---

package.json
yarn.lock

Bump the constants package to see the `load` network when searching for EVM-based chains

Bump constants package

---

src/pages/vincent-announcement.md

Remove `the` in Vincent announcement

---

docs/connecting-to-a-lit-network/mainnets.md
docs/connecting-to-a-lit-network/testnets.md

Update status page links for Datil networks

---

docs/intro/what-is-lit-protocol.md
src/pages/state-of-the-network.md

Add more use cases, edit the copy about what lit is

Changes to "what is lit" page
